package gui;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
import javax.swing.SwingUtilities;
import database.Database2;
import java.util.ArrayList;
import java.util.Vector;
public class ReceptionistUI extends javax.swing.JFrame {

    /**
     * Creates new form ReceptionistUI
     */
    public ReceptionistUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addButtonR = new javax.swing.JButton();
        updateButtonR = new javax.swing.JButton();
        deleteButtonR = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        addDoctor = new javax.swing.JButton();
        addStaff = new javax.swing.JButton();
        ViewDatabase = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addButtonR.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        addButtonR.setText("Add Patient");
        addButtonR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonRActionPerformed(evt);
            }
        });

        updateButtonR.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        updateButtonR.setText("Update Patient");
        updateButtonR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonRActionPerformed(evt);
            }
        });

        deleteButtonR.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        deleteButtonR.setText("Delete Patient");
        deleteButtonR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonRActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Chiller", 1, 36)); // NOI18N
        jLabel2.setText("Admin");

        addDoctor.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        addDoctor.setText("Add Doctor");
        addDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDoctorActionPerformed(evt);
            }
        });

        addStaff.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        addStaff.setText("Add Staff");
        addStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStaffActionPerformed(evt);
            }
        });

        ViewDatabase.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        ViewDatabase.setText("View Database");
        ViewDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewDatabaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(updateButtonR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(addButtonR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteButtonR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ViewDatabase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addStaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButtonR)
                    .addComponent(addDoctor))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateButtonR)
                    .addComponent(addStaff))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(deleteButtonR))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(ViewDatabase)))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonRActionPerformed
    
        AddPatient ap = new AddPatient();
        ap.setVisible(true);
    }//GEN-LAST:event_addButtonRActionPerformed

    private void updateButtonRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonRActionPerformed
        UpdateDeletePatient udp = new UpdateDeletePatient();
        udp.setVisible(true);
    }//GEN-LAST:event_updateButtonRActionPerformed

    private void deleteButtonRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonRActionPerformed
        // TODO add your handling code here:
        UpdateDeletePatient udp = new UpdateDeletePatient();
        udp.setVisible(true);
    }//GEN-LAST:event_deleteButtonRActionPerformed

    private void addDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDoctorActionPerformed
        // TODO add your handling code here:
        AddDoctor ad = new AddDoctor();
        ad.setVisible(true);
    }//GEN-LAST:event_addDoctorActionPerformed

    private void addStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStaffActionPerformed
        // TODO add your handling code here:
        AddStaff as = new AddStaff();
        as.setVisible(true);
    }//GEN-LAST:event_addStaffActionPerformed

    private void ViewDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewDatabaseActionPerformed
        // TODO add your handling code here:
        ArrayList<Vector> al = new ArrayList<>();
        Mainframe mf = new Mainframe(al);
        mf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ViewDatabaseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReceptionistUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReceptionistUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReceptionistUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReceptionistUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReceptionistUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ViewDatabase;
    private javax.swing.JButton addButtonR;
    private javax.swing.JButton addDoctor;
    private javax.swing.JButton addStaff;
    private javax.swing.JButton deleteButtonR;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton updateButtonR;
    // End of variables declaration//GEN-END:variables
}
